//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sautom.Client.Modules.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sautom.Client.Modules.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add order with new client.
        /// </summary>
        public static string Btn_AddClientOrder {
            get {
                return ResourceManager.GetString("Btn_AddClientOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new client.
        /// </summary>
        public static string Btn_AddNewClient {
            get {
                return ResourceManager.GetString("Btn_AddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add order.
        /// </summary>
        public static string Btn_AddOrderForClient {
            get {
                return ResourceManager.GetString("Btn_AddOrderForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline ticket.
        /// </summary>
        public static string Btn_AirlineTicketView {
            get {
                return ResourceManager.GetString("Btn_AirlineTicketView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to details.
        /// </summary>
        public static string Btn_BackToClientDetails {
            get {
                return ResourceManager.GetString("Btn_BackToClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Btn_BackToClients {
            get {
                return ResourceManager.GetString("Btn_BackToClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client details.
        /// </summary>
        public static string Btn_ClientDetails {
            get {
                return ResourceManager.GetString("Btn_ClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Btn_ClientTask {
            get {
                return ResourceManager.GetString("Btn_ClientTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract view.
        /// </summary>
        public static string Btn_ContractView {
            get {
                return ResourceManager.GetString("Btn_ContractView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        public static string Btn_DownloadFile {
            get {
                return ResourceManager.GetString("Btn_DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client.
        /// </summary>
        public static string Btn_EditClients {
            get {
                return ResourceManager.GetString("Btn_EditClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit or create.
        /// </summary>
        public static string Btn_EditOrCreate {
            get {
                return ResourceManager.GetString("Btn_EditOrCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print order info.
        /// </summary>
        public static string Btn_OrderInfoToPrint {
            get {
                return ResourceManager.GetString("Btn_OrderInfoToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print consulting.
        /// </summary>
        public static string Btn_PrintConsulting {
            get {
                return ResourceManager.GetString("Btn_PrintConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print workshop.
        /// </summary>
        public static string Btn_PrintWorkshop {
            get {
                return ResourceManager.GetString("Btn_PrintWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        public static string Btn_RemoveFile {
            get {
                return ResourceManager.GetString("Btn_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_SaveClientInfo {
            get {
                return ResourceManager.GetString("Btn_SaveClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new file.
        /// </summary>
        public static string Btn_UploadNewFile {
            get {
                return ResourceManager.GetString("Btn_UploadNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival city.
        /// </summary>
        public static string Label_ArrivalCity {
            get {
                return ResourceManager.GetString("Label_ArrivalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date.
        /// </summary>
        public static string Label_ArrivalDate {
            get {
                return ResourceManager.GetString("Label_ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string Label_BirthDate {
            get {
                return ResourceManager.GetString("Label_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking date.
        /// </summary>
        public static string Label_BookingDate {
            get {
                return ResourceManager.GetString("Label_BookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking expire date.
        /// </summary>
        public static string Label_BookingExpireDate {
            get {
                return ResourceManager.GetString("Label_BookingExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting act date.
        /// </summary>
        public static string Label_ConsultingActDate {
            get {
                return ResourceManager.GetString("Label_ConsultingActDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting date.
        /// </summary>
        public static string Label_ConsultingDate {
            get {
                return ResourceManager.GetString("Label_ConsultingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting hours.
        /// </summary>
        public static string Label_ConsultingHours {
            get {
                return ResourceManager.GetString("Label_ConsultingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting number.
        /// </summary>
        public static string Label_ConsultingNumber {
            get {
                return ResourceManager.GetString("Label_ConsultingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting sum.
        /// </summary>
        public static string Label_ConsultingSum {
            get {
                return ResourceManager.GetString("Label_ConsultingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract have not filled yet.
        /// </summary>
        public static string Label_ContractDoesNotFilled {
            get {
                return ResourceManager.GetString("Label_ContractDoesNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Label_CourseName {
            get {
                return ResourceManager.GetString("Label_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name.
        /// </summary>
        public static string Label_CourseNameFilter {
            get {
                return ResourceManager.GetString("Label_CourseNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure city.
        /// </summary>
        public static string Label_DepartureCity {
            get {
                return ResourceManager.GetString("Label_DepartureCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date.
        /// </summary>
        public static string Label_DepartureDate {
            get {
                return ResourceManager.GetString("Label_DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embassy date.
        /// </summary>
        public static string Label_EmbassyDate {
            get {
                return ResourceManager.GetString("Label_EmbassyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embasy docs.
        /// </summary>
        public static string Label_EmbasyDocs {
            get {
                return ResourceManager.GetString("Label_EmbasyDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House type.
        /// </summary>
        public static string Label_HouseType {
            get {
                return ResourceManager.GetString("Label_HouseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string Label_Intensity {
            get {
                return ResourceManager.GetString("Label_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice date.
        /// </summary>
        public static string Label_InvoiceDate {
            get {
                return ResourceManager.GetString("Label_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice sum.
        /// </summary>
        public static string Label_InvoiceSum {
            get {
                return ResourceManager.GetString("Label_InvoiceSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is embassy checked.
        /// </summary>
        public static string Label_IsEmbassyChecked {
            get {
                return ResourceManager.GetString("Label_IsEmbassyChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string Label_MiddleName {
            get {
                return ResourceManager.GetString("Label_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_NameEn {
            get {
                return ResourceManager.GetString("Label_NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name RUS.
        /// </summary>
        public static string Label_NameRu {
            get {
                return ResourceManager.GetString("Label_NameRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ru filter.
        /// </summary>
        public static string Label_NameRuFilter {
            get {
                return ResourceManager.GetString("Label_NameRuFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders count.
        /// </summary>
        public static string Label_OrdersCount {
            get {
                return ResourceManager.GetString("Label_OrdersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent address.
        /// </summary>
        public static string Label_ParentAddress {
            get {
                return ResourceManager.GetString("Label_ParentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent name.
        /// </summary>
        public static string Label_ParentName {
            get {
                return ResourceManager.GetString("Label_ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parrent passport.
        /// </summary>
        public static string Label_ParentPassportInfo {
            get {
                return ResourceManager.GetString("Label_ParentPassportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent phone.
        /// </summary>
        public static string Label_ParentPhone {
            get {
                return ResourceManager.GetString("Label_ParentPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport by date.
        /// </summary>
        public static string Label_PassportByDate {
            get {
                return ResourceManager.GetString("Label_PassportByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport by.
        /// </summary>
        public static string Label_PassportByWhom {
            get {
                return ResourceManager.GetString("Label_PassportByWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport from.
        /// </summary>
        public static string Label_PassportFromDate {
            get {
                return ResourceManager.GetString("Label_PassportFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport info.
        /// </summary>
        public static string Label_PassportInfo {
            get {
                return ResourceManager.GetString("Label_PassportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal number.
        /// </summary>
        public static string Label_PersonalNumber {
            get {
                return ResourceManager.GetString("Label_PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal number filter.
        /// </summary>
        public static string Label_PersonalNumberFilter {
            get {
                return ResourceManager.GetString("Label_PersonalNumberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Label_PhoneFirst {
            get {
                return ResourceManager.GetString("Label_PhoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second phone.
        /// </summary>
        public static string Label_PhoneSecond {
            get {
                return ResourceManager.GetString("Label_PhoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string Label_Proposal {
            get {
                return ResourceManager.GetString("Label_Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current rate.
        /// </summary>
        public static string Label_RateValue {
            get {
                return ResourceManager.GetString("Label_RateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redemption date.
        /// </summary>
        public static string Label_RedemptionDate {
            get {
                return ResourceManager.GetString("Label_RedemptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible manager.
        /// </summary>
        public static string Label_ResponsibleManager {
            get {
                return ResourceManager.GetString("Label_ResponsibleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string Label_SchoolName {
            get {
                return ResourceManager.GetString("Label_SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa date.
        /// </summary>
        public static string Label_VisaGetDate {
            get {
                return ResourceManager.GetString("Label_VisaGetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop act date.
        /// </summary>
        public static string Label_WorkshopActDate {
            get {
                return ResourceManager.GetString("Label_WorkshopActDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop date.
        /// </summary>
        public static string Label_WorkshopDate {
            get {
                return ResourceManager.GetString("Label_WorkshopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop hours.
        /// </summary>
        public static string Label_WorkshopHours {
            get {
                return ResourceManager.GetString("Label_WorkshopHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop number.
        /// </summary>
        public static string Label_WorkshopNumber {
            get {
                return ResourceManager.GetString("Label_WorkshopNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop sum.
        /// </summary>
        public static string Label_WorkshopSum {
            get {
                return ResourceManager.GetString("Label_WorkshopSum", resourceCulture);
            }
        }
    }
}
