//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sautom.Client.Modules.Proposal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sautom.Client.Modules.Proposal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to proposals.
        /// </summary>
        public static string BackToProposals {
            get {
                return ResourceManager.GetString("BackToProposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add city.
        /// </summary>
        public static string Btn_AddCity {
            get {
                return ResourceManager.GetString("Btn_AddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document.
        /// </summary>
        public static string Btn_AddDocument {
            get {
                return ResourceManager.GetString("Btn_AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rate.
        /// </summary>
        public static string Btn_AddRate {
            get {
                return ResourceManager.GetString("Btn_AddRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries list.
        /// </summary>
        public static string Btn_CountriesList {
            get {
                return ResourceManager.GetString("Btn_CountriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create country.
        /// </summary>
        public static string Btn_CreateCountry {
            get {
                return ResourceManager.GetString("Btn_CreateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create proposal.
        /// </summary>
        public static string Btn_CreateProposal {
            get {
                return ResourceManager.GetString("Btn_CreateProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contry.
        /// </summary>
        public static string Btn_EditContry {
            get {
                return ResourceManager.GetString("Btn_EditContry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit proposal.
        /// </summary>
        public static string Btn_EditProposal {
            get {
                return ResourceManager.GetString("Btn_EditProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposals.
        /// </summary>
        public static string Btn_ProposalTask {
            get {
                return ResourceManager.GetString("Btn_ProposalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Label_Cities {
            get {
                return ResourceManager.GetString("Label_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Label_City {
            get {
                return ResourceManager.GetString("Label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country filter.
        /// </summary>
        public static string Label_CountryFilter {
            get {
                return ResourceManager.GetString("Label_CountryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name.
        /// </summary>
        public static string Label_CourseName {
            get {
                return ResourceManager.GetString("Label_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name filter.
        /// </summary>
        public static string Label_CourseNameFilter {
            get {
                return ResourceManager.GetString("Label_CourseNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curator name.
        /// </summary>
        public static string Label_CuratorName {
            get {
                return ResourceManager.GetString("Label_CuratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Label_Documents {
            get {
                return ResourceManager.GetString("Label_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing type.
        /// </summary>
        public static string Label_HousingTypes {
            get {
                return ResourceManager.GetString("Label_HousingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string Label_Intensity {
            get {
                return ResourceManager.GetString("Label_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program type filter:.
        /// </summary>
        public static string Label_ProgramTypeFilter {
            get {
                return ResourceManager.GetString("Label_ProgramTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Label_ProposalGroupType {
            get {
                return ResourceManager.GetString("Label_ProposalGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Label_ProposalIndividualType {
            get {
                return ResourceManager.GetString("Label_ProposalIndividualType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal type.
        /// </summary>
        public static string Label_ProposalType {
            get {
                return ResourceManager.GetString("Label_ProposalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate value.
        /// </summary>
        public static string Label_RateValue {
            get {
                return ResourceManager.GetString("Label_RateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School name.
        /// </summary>
        public static string Label_SchoolName {
            get {
                return ResourceManager.GetString("Label_SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School name filter.
        /// </summary>
        public static string Label_SchoolNameFilter {
            get {
                return ResourceManager.GetString("Label_SchoolNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start from date.
        /// </summary>
        public static string Label_StartFromDate {
            get {
                return ResourceManager.GetString("Label_StartFromDate", resourceCulture);
            }
        }
    }
}
