//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sautom.Client.Comunication.CommandService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProposalEditDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class ProposalEditDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuratorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] HouseTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] IntensitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGroupTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuratorName {
            get {
                return this.CuratorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CuratorNameField, value) != true)) {
                    this.CuratorNameField = value;
                    this.RaisePropertyChanged("CuratorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] HouseTypes {
            get {
                return this.HouseTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseTypesField, value) != true)) {
                    this.HouseTypesField = value;
                    this.RaisePropertyChanged("HouseTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] Intensities {
            get {
                return this.IntensitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.IntensitiesField, value) != true)) {
                    this.IntensitiesField = value;
                    this.RaisePropertyChanged("Intensities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGroupType {
            get {
                return this.IsGroupTypeField;
            }
            set {
                if ((this.IsGroupTypeField.Equals(value) != true)) {
                    this.IsGroupTypeField = value;
                    this.RaisePropertyChanged("IsGroupType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolName {
            get {
                return this.SchoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolNameField, value) != true)) {
                    this.SchoolNameField = value;
                    this.RaisePropertyChanged("SchoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderEditDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class OrderEditDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EmbassyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] EmbassyDocsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid HouseTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IntensityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsEmbassyCheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProposalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VisaDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmbassyDate {
            get {
                return this.EmbassyDateField;
            }
            set {
                if ((this.EmbassyDateField.Equals(value) != true)) {
                    this.EmbassyDateField = value;
                    this.RaisePropertyChanged("EmbassyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] EmbassyDocs {
            get {
                return this.EmbassyDocsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmbassyDocsField, value) != true)) {
                    this.EmbassyDocsField = value;
                    this.RaisePropertyChanged("EmbassyDocs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid HouseTypeId {
            get {
                return this.HouseTypeIdField;
            }
            set {
                if ((this.HouseTypeIdField.Equals(value) != true)) {
                    this.HouseTypeIdField = value;
                    this.RaisePropertyChanged("HouseTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IntensityId {
            get {
                return this.IntensityIdField;
            }
            set {
                if ((this.IntensityIdField.Equals(value) != true)) {
                    this.IntensityIdField = value;
                    this.RaisePropertyChanged("IntensityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsEmbassyChecked {
            get {
                return this.IsEmbassyCheckedField;
            }
            set {
                if ((this.IsEmbassyCheckedField.Equals(value) != true)) {
                    this.IsEmbassyCheckedField = value;
                    this.RaisePropertyChanged("IsEmbassyChecked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProposalId {
            get {
                return this.ProposalIdField;
            }
            set {
                if ((this.ProposalIdField.Equals(value) != true)) {
                    this.ProposalIdField = value;
                    this.RaisePropertyChanged("ProposalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VisaDate {
            get {
                return this.VisaDateField;
            }
            set {
                if ((this.VisaDateField.Equals(value) != true)) {
                    this.VisaDateField = value;
                    this.RaisePropertyChanged("VisaDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientEditDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class ClientEditDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameLatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sautom.Client.Comunication.CommandService.OrderEditDtoInput OrderInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentPassportInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PassportByDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportByWhomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PassportFromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneFirstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneSecondField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameLat {
            get {
                return this.NameLatField;
            }
            set {
                if ((object.ReferenceEquals(this.NameLatField, value) != true)) {
                    this.NameLatField = value;
                    this.RaisePropertyChanged("NameLat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sautom.Client.Comunication.CommandService.OrderEditDtoInput OrderInfo {
            get {
                return this.OrderInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderInfoField, value) != true)) {
                    this.OrderInfoField = value;
                    this.RaisePropertyChanged("OrderInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentAddress {
            get {
                return this.ParentAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentAddressField, value) != true)) {
                    this.ParentAddressField = value;
                    this.RaisePropertyChanged("ParentAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentName {
            get {
                return this.ParentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentNameField, value) != true)) {
                    this.ParentNameField = value;
                    this.RaisePropertyChanged("ParentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentPassportInfo {
            get {
                return this.ParentPassportInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentPassportInfoField, value) != true)) {
                    this.ParentPassportInfoField = value;
                    this.RaisePropertyChanged("ParentPassportInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentPhone {
            get {
                return this.ParentPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentPhoneField, value) != true)) {
                    this.ParentPhoneField = value;
                    this.RaisePropertyChanged("ParentPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PassportByDate {
            get {
                return this.PassportByDateField;
            }
            set {
                if ((this.PassportByDateField.Equals(value) != true)) {
                    this.PassportByDateField = value;
                    this.RaisePropertyChanged("PassportByDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportByWhom {
            get {
                return this.PassportByWhomField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportByWhomField, value) != true)) {
                    this.PassportByWhomField = value;
                    this.RaisePropertyChanged("PassportByWhom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PassportFromDate {
            get {
                return this.PassportFromDateField;
            }
            set {
                if ((this.PassportFromDateField.Equals(value) != true)) {
                    this.PassportFromDateField = value;
                    this.RaisePropertyChanged("PassportFromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportInfo {
            get {
                return this.PassportInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportInfoField, value) != true)) {
                    this.PassportInfoField = value;
                    this.RaisePropertyChanged("PassportInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalNumber {
            get {
                return this.PersonalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalNumberField, value) != true)) {
                    this.PersonalNumberField = value;
                    this.RaisePropertyChanged("PersonalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneFirst {
            get {
                return this.PhoneFirstField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneFirstField, value) != true)) {
                    this.PhoneFirstField = value;
                    this.RaisePropertyChanged("PhoneFirst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneSecond {
            get {
                return this.PhoneSecondField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneSecondField, value) != true)) {
                    this.PhoneSecondField = value;
                    this.RaisePropertyChanged("PhoneSecond");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounrtyEditDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class CounrtyEditDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sautom.Client.Comunication.CommandService.CityItemDtoInput[] CitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sautom.Client.Comunication.CommandService.EmbassyDocumentItemDtoInput[] EmbassyDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sautom.Client.Comunication.CommandService.CityItemDtoInput[] Cities {
            get {
                return this.CitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CitiesField, value) != true)) {
                    this.CitiesField = value;
                    this.RaisePropertyChanged("Cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sautom.Client.Comunication.CommandService.EmbassyDocumentItemDtoInput[] EmbassyDocuments {
            get {
                return this.EmbassyDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmbassyDocumentsField, value) != true)) {
                    this.EmbassyDocumentsField = value;
                    this.RaisePropertyChanged("EmbassyDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityItemDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class CityItemDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmbassyDocumentItemDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class EmbassyDocumentItemDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArchivalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArchival {
            get {
                return this.IsArchivalField;
            }
            set {
                if ((this.IsArchivalField.Equals(value) != true)) {
                    this.IsArchivalField = value;
                    this.RaisePropertyChanged("IsArchival");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateItemDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class RateItemDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RateValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float RateValue {
            get {
                return this.RateValueField;
            }
            set {
                if ((this.RateValueField.Equals(value) != true)) {
                    this.RateValueField = value;
                    this.RaisePropertyChanged("RateValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractEditDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class ContractEditDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ConsultingActDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ConsultingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ConsultingHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sautom.Client.Comunication.CommandService.RateItemDtoInput ConsultingRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ConsultingSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> WorkshopActDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> WorkshopDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float WorkshopHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkshopNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sautom.Client.Comunication.CommandService.RateItemDtoInput WorkshopRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float WorkshopSumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConsultingActDate {
            get {
                return this.ConsultingActDateField;
            }
            set {
                if ((this.ConsultingActDateField.Equals(value) != true)) {
                    this.ConsultingActDateField = value;
                    this.RaisePropertyChanged("ConsultingActDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConsultingDate {
            get {
                return this.ConsultingDateField;
            }
            set {
                if ((this.ConsultingDateField.Equals(value) != true)) {
                    this.ConsultingDateField = value;
                    this.RaisePropertyChanged("ConsultingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ConsultingHours {
            get {
                return this.ConsultingHoursField;
            }
            set {
                if ((this.ConsultingHoursField.Equals(value) != true)) {
                    this.ConsultingHoursField = value;
                    this.RaisePropertyChanged("ConsultingHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultingNumber {
            get {
                return this.ConsultingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultingNumberField, value) != true)) {
                    this.ConsultingNumberField = value;
                    this.RaisePropertyChanged("ConsultingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sautom.Client.Comunication.CommandService.RateItemDtoInput ConsultingRate {
            get {
                return this.ConsultingRateField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultingRateField, value) != true)) {
                    this.ConsultingRateField = value;
                    this.RaisePropertyChanged("ConsultingRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ConsultingSum {
            get {
                return this.ConsultingSumField;
            }
            set {
                if ((this.ConsultingSumField.Equals(value) != true)) {
                    this.ConsultingSumField = value;
                    this.RaisePropertyChanged("ConsultingSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceSum {
            get {
                return this.InvoiceSumField;
            }
            set {
                if ((this.InvoiceSumField.Equals(value) != true)) {
                    this.InvoiceSumField = value;
                    this.RaisePropertyChanged("InvoiceSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> WorkshopActDate {
            get {
                return this.WorkshopActDateField;
            }
            set {
                if ((this.WorkshopActDateField.Equals(value) != true)) {
                    this.WorkshopActDateField = value;
                    this.RaisePropertyChanged("WorkshopActDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> WorkshopDate {
            get {
                return this.WorkshopDateField;
            }
            set {
                if ((this.WorkshopDateField.Equals(value) != true)) {
                    this.WorkshopDateField = value;
                    this.RaisePropertyChanged("WorkshopDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float WorkshopHours {
            get {
                return this.WorkshopHoursField;
            }
            set {
                if ((this.WorkshopHoursField.Equals(value) != true)) {
                    this.WorkshopHoursField = value;
                    this.RaisePropertyChanged("WorkshopHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkshopNumber {
            get {
                return this.WorkshopNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkshopNumberField, value) != true)) {
                    this.WorkshopNumberField = value;
                    this.RaisePropertyChanged("WorkshopNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sautom.Client.Comunication.CommandService.RateItemDtoInput WorkshopRate {
            get {
                return this.WorkshopRateField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkshopRateField, value) != true)) {
                    this.WorkshopRateField = value;
                    this.RaisePropertyChanged("WorkshopRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float WorkshopSum {
            get {
                return this.WorkshopSumField;
            }
            set {
                if ((this.WorkshopSumField.Equals(value) != true)) {
                    this.WorkshopSumField = value;
                    this.RaisePropertyChanged("WorkshopSum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirlineTicketEditDtoInput", Namespace="http://schemas.datacontract.org/2004/07/Sautom.WcfServer.TransportDto")]
    [System.SerializableAttribute()]
    public partial class AirlineTicketEditDtoInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ArrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BookingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BookingExpireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RedemptionDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrivalCity {
            get {
                return this.ArrivalCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalCityField, value) != true)) {
                    this.ArrivalCityField = value;
                    this.RaisePropertyChanged("ArrivalCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((this.ArrivalDateField.Equals(value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BookingDate {
            get {
                return this.BookingDateField;
            }
            set {
                if ((this.BookingDateField.Equals(value) != true)) {
                    this.BookingDateField = value;
                    this.RaisePropertyChanged("BookingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BookingExpireDate {
            get {
                return this.BookingExpireDateField;
            }
            set {
                if ((this.BookingExpireDateField.Equals(value) != true)) {
                    this.BookingExpireDateField = value;
                    this.RaisePropertyChanged("BookingExpireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureCity {
            get {
                return this.DepartureCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureCityField, value) != true)) {
                    this.DepartureCityField = value;
                    this.RaisePropertyChanged("DepartureCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RedemptionDate {
            get {
                return this.RedemptionDateField;
            }
            set {
                if ((this.RedemptionDateField.Equals(value) != true)) {
                    this.RedemptionDateField = value;
                    this.RaisePropertyChanged("RedemptionDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommandService.ICommandService")]
    public interface ICommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/ProposalEditOrAdd", ReplyAction="http://tempuri.org/ICommandService/ProposalEditOrAddResponse")]
        bool ProposalEditOrAdd(Sautom.Client.Comunication.CommandService.ProposalEditDtoInput data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/AddOrder", ReplyAction="http://tempuri.org/ICommandService/AddOrderResponse")]
        bool AddOrder(System.Guid clientId, Sautom.Client.Comunication.CommandService.OrderEditDtoInput orderData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/UpdateOrder", ReplyAction="http://tempuri.org/ICommandService/UpdateOrderResponse")]
        bool UpdateOrder(Sautom.Client.Comunication.CommandService.OrderEditDtoInput orderData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/EditOrAddClient", ReplyAction="http://tempuri.org/ICommandService/EditOrAddClientResponse")]
        bool EditOrAddClient(System.Guid clientId, Sautom.Client.Comunication.CommandService.ClientEditDtoInput clientData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/EditOrAddCountry", ReplyAction="http://tempuri.org/ICommandService/EditOrAddCountryResponse")]
        bool EditOrAddCountry(Sautom.Client.Comunication.CommandService.CounrtyEditDtoInput data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/EditOrAddRate", ReplyAction="http://tempuri.org/ICommandService/EditOrAddRateResponse")]
        bool EditOrAddRate(Sautom.Client.Comunication.CommandService.RateItemDtoInput data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/BulkUpdateOrders", ReplyAction="http://tempuri.org/ICommandService/BulkUpdateOrdersResponse")]
        bool BulkUpdateOrders(Sautom.Client.Comunication.CommandService.OrderEditDtoInput[] orders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/EditOrAddContract", ReplyAction="http://tempuri.org/ICommandService/EditOrAddContractResponse")]
        bool EditOrAddContract(Sautom.Client.Comunication.CommandService.ContractEditDtoInput contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/EditOrAddAirlineTicket", ReplyAction="http://tempuri.org/ICommandService/EditOrAddAirlineTicketResponse")]
        bool EditOrAddAirlineTicket(Sautom.Client.Comunication.CommandService.AirlineTicketEditDtoInput airlineTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/AddClientComment", ReplyAction="http://tempuri.org/ICommandService/AddClientCommentResponse")]
        bool AddClientComment(System.Guid clientId, string comment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommandServiceChannel : Sautom.Client.Comunication.CommandService.ICommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandServiceClient : System.ServiceModel.ClientBase<Sautom.Client.Comunication.CommandService.ICommandService>, Sautom.Client.Comunication.CommandService.ICommandService {
        
        public CommandServiceClient() {
        }
        
        public CommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ProposalEditOrAdd(Sautom.Client.Comunication.CommandService.ProposalEditDtoInput data) {
            return base.Channel.ProposalEditOrAdd(data);
        }
        
        public bool AddOrder(System.Guid clientId, Sautom.Client.Comunication.CommandService.OrderEditDtoInput orderData) {
            return base.Channel.AddOrder(clientId, orderData);
        }
        
        public bool UpdateOrder(Sautom.Client.Comunication.CommandService.OrderEditDtoInput orderData) {
            return base.Channel.UpdateOrder(orderData);
        }
        
        public bool EditOrAddClient(System.Guid clientId, Sautom.Client.Comunication.CommandService.ClientEditDtoInput clientData) {
            return base.Channel.EditOrAddClient(clientId, clientData);
        }
        
        public bool EditOrAddCountry(Sautom.Client.Comunication.CommandService.CounrtyEditDtoInput data) {
            return base.Channel.EditOrAddCountry(data);
        }
        
        public bool EditOrAddRate(Sautom.Client.Comunication.CommandService.RateItemDtoInput data) {
            return base.Channel.EditOrAddRate(data);
        }
        
        public bool BulkUpdateOrders(Sautom.Client.Comunication.CommandService.OrderEditDtoInput[] orders) {
            return base.Channel.BulkUpdateOrders(orders);
        }
        
        public bool EditOrAddContract(Sautom.Client.Comunication.CommandService.ContractEditDtoInput contract) {
            return base.Channel.EditOrAddContract(contract);
        }
        
        public bool EditOrAddAirlineTicket(Sautom.Client.Comunication.CommandService.AirlineTicketEditDtoInput airlineTicket) {
            return base.Channel.EditOrAddAirlineTicket(airlineTicket);
        }
        
        public bool AddClientComment(System.Guid clientId, string comment) {
            return base.Channel.AddClientComment(clientId, comment);
        }
    }
}
